[package]
name = "nmap-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.28", features = ["default"] }
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"